<a href="https://colab.research.google.com/github/mayowaawo/sql-for-data-analysis-3271025/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch fundamentals

In [82]:
print("Hello world, I'm excited to learn pytorch")

Hello world, I'm excited to learn pytorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


##Intro to Tensors
A tensor is an expression of data using numbers


### creating tensors

In [3]:
#scalar: a quantity described only by magnitude. its a single number
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim #a scalar has 0 dimension because it has no indeces

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector: a quantity that has both magnitute and direction. how far something is going and what direction it's going in e.g velocity
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim #number of dimensions, think of this as number of square bracket pair[]

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix: a rectangular arrangement of numbers or symbols in rows and columns
MATRIX = torch.tensor([[7,8],
                      [9,10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#tensor
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,6,9,5],
                        [2,4,5,6],
                        [5,6,7,8],
                        [9,9,9,9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape #this [1,3,3] means we have 1 [3,3] dimensional data

torch.Size([1, 5, 4])

### Random Tensors
#### why random tensors?
#### Random tensors are important because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers` this is how neural networks works

In [17]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4524, 0.7281, 0.5252, 0.5226],
        [0.6197, 0.0858, 0.4590, 0.5103],
        [0.7489, 0.6202, 0.1906, 0.4819]])

In [18]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #color chanels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [19]:
#create a tensor of all zeros usually used to mask the numbers (telling tensor to ignore)
zeros = torch.zeros(3,4,10)
zeros

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [20]:
#create a tensor of all ones
ones = torch.ones(3,4,90)
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [21]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [22]:
#use torch.arange
one_to_ten = torch.arange(start= 0, end= 100, step =5)
one_to_ten

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [23]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
***Note:*** Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [24]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,              #what datatype the tesnsor are (default is 32)
                               device= 'cpu',             #what device the tensor is on
                               requires_grad=False)     #whether or not to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_32_tensor.dtype #this is because the default data type used in torch is float 32

torch.float16

In [26]:
float_16_tensor = float_32_tensor.type(torch.half)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

###Getting information from tensors (attributes)
1. To get datatype from a tensor use `tensor.dtype`
2. To get shape from a tensor use `tensor.shape`
3. To get device from a tensor use `tensor.devixe`

In [28]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8648, 0.0891, 0.2660, 0.2834],
        [0.8450, 0.0314, 0.6733, 0.9318],
        [0.5153, 0.3898, 0.2514, 0.5329]])

In [29]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8648, 0.0891, 0.2660, 0.2834],
        [0.8450, 0.0314, 0.6733, 0.9318],
        [0.5153, 0.3898, 0.2514, 0.5329]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
Tensor operations include:

*   Addition
*   Subtraction   
*   Multiplication (element-wise)
*   Division



*   Matrix multiplication









In [30]:
#addition: create a tensor and add ten to it
tensor = torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [31]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [32]:
#subtract 10
tensor-10

tensor([-9, -8, -7])

In [33]:
#try out pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
torch.add(tensor,10)

tensor([11, 12, 13])

###Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy;
1. The **inner dimensions** must match:

`@` is the symbol for matrix operation in python

*   `(3,2) @ (3,2)` won't work

*   `(2,3) @ (3,2)` will work
*   `(3,2) @ (2,3)` will work

Inner dimensions are the numbers closest to the `@` symbol. They must match for a matrix multiplication to work

2. The resulting matrix has the shape of the **outer dimensions**:


*   `(2,3) @ (3,2) -> (2,2)`
*   `(3,2) @ (2,3) -> (3,3)`





In [35]:
#element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
#matrix multiplication
matrix_mul = torch.rand(1,3)
matrix_mul2 = torch.rand(3,1)
torch.matmul(matrix_mul, matrix_mul2)

tensor([[0.6564]])

In [37]:
#matrix multiplication
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [38]:
#matrix multiplication
1*1 + 2*2 + 3*3

14

In [39]:
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs
tensor(14)


In [40]:
%time
torch.matmul(tensor, tensor) #compute time is faster using built in torch function

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


tensor(14)

In [41]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

###To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose
A **transpose** switches the axes or dimensions of a given tensor

In [42]:
tensor_B.T.shape

torch.Size([2, 3])

In [43]:
#the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [44]:
#playing around with mm
tensor_C = torch.rand(10,3)
tensor_D = torch.rand(2,10)
torch.mm(tensor_C, tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x3 and 2x10)

In [65]:
#inner dimensions gotta match
torch.mm(tensor_C.T, tensor_D.T)

tensor([[3.9385, 2.2599],
        [3.2631, 2.1291],
        [3.5936, 2.6914]])

###Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
#find the minimum
torch.min(x) or x.min()

tensor(0)

In [68]:
#find the max
torch.max(x) or x.max()

tensor(90)

In [69]:
#find the mean: the torch.mean function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) or x.type(torch.float32).mean()

tensor(45.)

In [70]:
#find the sum
torch.sum(x) or x.sum()

tensor(450)

In [71]:
#find the position in tensor that has the minimum and maximum value with argmin <- returns index value
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [72]:
x[0], x[9]

(tensor(0), tensor(90))

###Reshaping, stacking, squeezing and unsqueezing tensors


*   Reshaping - reshapes an input tensor to a defined shape
*   View- return a view of an input tensor of certain shape but keep the same memory as the original tensor


*   Stacking 0 combine multiple tensors on top of each other (vstack) or side by side (hstack)
*   Squeeze - removes all `1` dimensions from a tensor


*   Unsqueeze - add a `1` dimension to a target tensor


*   Permute - Return a view of the input with dimensions permuted (swapped) in a certain way











In [73]:
#create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
#changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
#stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
#torch.squeeze() -remove a single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [79]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [80]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [81]:
x_original[0,0,0] = 89298
x_original[0,0,0], x_permuted[0,0,0]

(tensor(89298.), tensor(89298.))

In [82]:
x_original[0,0,1] = 9842
x_original[0,0,1]
x_permuted[0,0,1]

tensor(0.5813)

###Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with NumPy

In [83]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
#let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [86]:
#let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [87]:
#you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [88]:
#get all the values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [89]:
#get all values from the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [90]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [91]:
#index on x to return 9
x[0][2][2], x[:,2,2]

(tensor(9), tensor([9]))

In [92]:
#index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

###PyTorch tensors and NumPy
NumPy is a popular scientific python numerical computing library. And because of this, PyTorch has functionality to interact with it.


*   Data in NumPy, want in pytorch tensor -> `torch.from_numpy(ndarrary)`
*   PyTorch tensor to Numpy -> `torch.Tensor.numpy()`



In [93]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
#change the value of the array, what will this do to tensor? nothing
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
numpy_tensor.dtype

dtype('float32')

In [97]:
#change the tensor, what happens to numpy_tensor? nothing
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of randomness)
In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of data -> again -> again -> again...`

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

Essentially what random seed does is flavor the randomness

In [99]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5207, 0.3548, 0.8912, 0.4898],
        [0.7341, 0.9961, 0.7293, 0.5423],
        [0.4411, 0.6721, 0.6974, 0.4444]])
tensor([[0.8522, 0.6563, 0.6422, 0.1024],
        [0.5623, 0.0054, 0.6263, 0.1633],
        [0.1106, 0.9393, 0.6426, 0.5729]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [101]:
#let's make some random n=but reproducible tensors
import torch

#set random seed
random_seed = 1234
torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)


tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scences to make everything good

1. Easiest- use google colab for a free gpu
2. Use your own GPU- takes a little bit of setup and requires the investment of purchse of a gpu
3. Use cloud computing - GCP, AWS, Azure

In [2]:
!nvidia-smi

Fri Sep 26 01:34:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

###Check for GPU access with PyTorch

In [5]:
#check for gpu access with PyTorch
import torch
torch.cuda.is_available()

True

In [6]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
#count number of devices
torch.cuda.device_count()

1

##3. Putting tensors (models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [16]:
#create a tensor (default on cpu)
tensor = torch.tensor([1,2,3])

#tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [17]:
#move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

##4. Moving tensors back to the CPU

In [21]:
#if tensor is on gpu, can't transform it to NumPy
# tensor_on_gpu.numpy() # This will produce an error

tensor_back_on_cpu = tensor_on_gpu.numpy()
tensor_back_on_cpu

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [19]:
#to fix the GOU tensor with numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [22]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Exercises and Extra-curriculum

### Exercise 1

In [26]:
#1. Create a random tensor with shape (7, 7)
import torch
a = torch.rand(7,7)
a

tensor([[0.6321, 0.1080, 0.3381, 0.8820, 0.0467, 0.5654, 0.9760],
        [0.9452, 0.2435, 0.6657, 0.5206, 0.6717, 0.1642, 0.7045],
        [0.9920, 0.0286, 0.8422, 0.0730, 0.5843, 0.2657, 0.8706],
        [0.9435, 0.9556, 0.9175, 0.0149, 0.7510, 0.5509, 0.0582],
        [0.5657, 0.3890, 0.2699, 0.3949, 0.8574, 0.6658, 0.3997],
        [0.4932, 0.6147, 0.2100, 0.6042, 0.3631, 0.0931, 0.4235],
        [0.9501, 0.0148, 0.6845, 0.3712, 0.1938, 0.3525, 0.0630]])

In [40]:
#2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
b = torch.rand(1,7).T #transpose to get required shape for matrix multiplication
c = torch.matmul(a,b)
c

tensor([[1.1173],
        [1.7231],
        [1.4061],
        [1.9499],
        [0.9564],
        [1.3146],
        [1.1037]])

In [39]:
#3. Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
a = torch.rand(7,7)

torch.manual_seed(0)
b = torch.rand(1,7).T

c = torch.matmul(a,b)
c

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [43]:
#4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [66]:
#5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

torch.cuda.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(42)
random_tensor_a = torch.rand((2,3), device=device)

torch.manual_seed(42)
random_tensor_b = torch.rand(2,3).to(device)

random_tensor_a, random_tensor_b


(tensor([[0.6130, 0.0101, 0.3984],
         [0.0403, 0.1563, 0.4825]], device='cuda:0'),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]], device='cuda:0'))

In [71]:
#6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
random_tensor_b = random_tensor_b.T
random_tensor_c = torch.matmul(random_tensor_a, random_tensor_b)

In [72]:
#7. Find the maximum and minimum values of the output of 7.
print(f"Max value: {random_tensor_c.max()}, Min values: {random_tensor_c.min()}")

Max value: 0.8313482403755188, Min values: 0.36326900124549866


In [73]:
#8. Find the maximum and minimum index values of the output of 7.
print(f"Max value: {random_tensor_c.argmax()}, Min values: {random_tensor_c.argmin()}")

Max value: 1, Min values: 2


In [81]:
#9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
random_tensor_x = torch.rand(1,1,1,10)

torch.manual_seed(7)
random_tensor_y = random_tensor_x.squeeze()

print(f"First tensor: {random_tensor_x}, First tensor shape: {random_tensor_x.shape},\n Second tensor: {random_tensor_y}, Second tensor shape: {random_tensor_y.shape}")

First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), First tensor shape: torch.Size([1, 1, 1, 10]),
 Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), Second tensor shape: torch.Size([10])
